DELETE FROM PRICE_MSTR;
DELETE FROM TKT;
DELETE FROM TRN;
DELETE FROM SMS;
UPDATE ENT_ID_GEN SET CURR_ID=5;

Insert into RLY_STN (STN_CODE, STN_NAME) VALUES('KLYN', 'Kalyan');
Insert into RLY_STN (STN_CODE, STN_NAME) VALUES('DOM', 'Dombivali');
Insert into RLY_STN (STN_CODE, STN_NAME) VALUES('THN', 'Thane');
Insert into RLY_STN (STN_CODE, STN_NAME) VALUES('DDR', 'Dadar');
Insert into RLY_STN (STN_CODE, STN_NAME) VALUES('CST', 'VT');

Insert into PRICE_MSTR (ID,FK_FROM_STN_ID,PRICE,FK_TO_STN_ID) values (1,'KLYN',5,'DOM');
Insert into PRICE_MSTR (ID,FK_FROM_STN_ID,PRICE,FK_TO_STN_ID) values (2,'KLYN',10,'THN');
Insert into PRICE_MSTR (ID,FK_FROM_STN_ID,PRICE,FK_TO_STN_ID) values (3,'KLYN',15,'DDR');
Insert into PRICE_MSTR (ID,FK_FROM_STN_ID,PRICE,FK_TO_STN_ID) values (4,'KLYN',20,'CST');


Insert into SMS (ID,BODY,MOBILE,STATUS,TYP,FK_ACC_ID) values (1,'TKT book KLYN DOM 1',9930783001,1,0,2);
Insert into SMS (ID,BODY,MOBILE,STATUS,TYP,FK_ACC_ID) values (2,'TKT book KLYN THN 1',9930783001,1,0,2);
Insert into SMS (ID,BODY,MOBILE,STATUS,TYP,FK_ACC_ID) values (3,'TKT book KLYN DDR 1',9930783001,1,0,2);
Insert into SMS (ID,BODY,MOBILE,STATUS,TYP,FK_ACC_ID) values (4,'TKT book KLYN CST 1',9930783001,1,0,2);

Insert into TRN (ID,AMT,CRT_TIME,TRN_TYP,FK_ACC_ID) values (1,5,to_timestamp('10-APR-2013','DD-MON-YYYY'),1,2);
Insert into TRN (ID,AMT,CRT_TIME,TRN_TYP,FK_ACC_ID) values (2,10,to_timestamp('10-APR-2013','DD-MON-YYYY'),1,2);
Insert into TRN (ID,AMT,CRT_TIME,TRN_TYP,FK_ACC_ID) values (3,15,to_timestamp('10-APR-2013','DD-MON-YYYY'),1,2);
Insert into TRN (ID,AMT,CRT_TIME,TRN_TYP,FK_ACC_ID) values (4,20,to_timestamp('10-APR-2013','DD-MON-YYYY'),1,2);

Insert into TKT (ID,CRTD_TIME,AMT,FRM_STN,NO_OF_TKT,TO_STN,FK_IN_TKT_SMS_ID,FK_OUT_TKT_SMS_ID) 
values (1,to_timestamp('10-APR-2013','DD-MON-YYYY'),5,'KLYN',1,'DOM',1,null);

Insert into TKT (ID,CRTD_TIME,AMT,FRM_STN,NO_OF_TKT,TO_STN,FK_IN_TKT_SMS_ID,FK_OUT_TKT_SMS_ID) 
values (2,to_timestamp('10-APR-2013','DD-MON-YYYY'),10,'KLYN',1,'THN',2,null);

Insert into TKT (ID,CRTD_TIME,AMT,FRM_STN,NO_OF_TKT,TO_STN,FK_IN_TKT_SMS_ID,FK_OUT_TKT_SMS_ID) 
values (3,to_timestamp('10-APR-2013','DD-MON-YYYY'),15,'KLYN',1,'DDR',3,null);

Insert into TKT (ID,CRTD_TIME,AMT,FRM_STN,NO_OF_TKT,TO_STN,FK_IN_TKT_SMS_ID,FK_OUT_TKT_SMS_ID) 
values (4,to_timestamp('10-APR-2013','DD-MON-YYYY'),20,'KLYN',1,'CST',4,null);

commit;