DROP TABLE ACC CASCADE CONSTRAINT;
DROP TABLE PRICE_MSTR CASCADE CONSTRAINT;
DROP TABLE SMS CASCADE CONSTRAINT;
DROP TABLE TKT CASCADE CONSTRAINT;
DROP TABLE TRN CASCADE CONSTRAINT;
DROP TABLE ENT_ID_GEN CASCADE CONSTRAINT;
/

CREATE TABLE  ACC 
   (	
   	ID NUMBER(19,0) NOT NULL ENABLE, 
	BAL NUMBER(19,2) NOT NULL , 
	CRTD_TIME TIMESTAMP (6), 
	MOB VARCHAR2(255 CHAR), 
	UPDT_TIME TIMESTAMP (6), 
	PASSWD VARCHAR2(255 CHAR), 
	ROLE NUMBER(1,0), 
	STATUS NUMBER(1,0), 
	USR_NAM VARCHAR2(255 CHAR), 
	
	PRIMARY KEY (ID) ENABLE, 
	UNIQUE (USR_NAM) ENABLE,
	UNIQUE (MOB) ENABLE
   )
/

CREATE TABLE  ENT_ID_GEN 
   (	
    ENT_NAM VARCHAR2(255 CHAR), 
	CURR_ID NUMBER(19,0)
   )
/

CREATE TABLE  PRICE_MSTR 
   (	
   	ID NUMBER(19,0) NOT NULL ENABLE, 
	FRM_STN_CDE VARCHAR2(255 CHAR), 
	PRICE NUMBER(19,2), 
	TO_STN_CDE VARCHAR2(255 CHAR), 
	
	PRIMARY KEY (ID) ENABLE
   )
/

CREATE TABLE  SMS 
   (	
  	ID NUMBER(19,0) NOT NULL ENABLE, 
	BODY VARCHAR2(255 CHAR), 
	MOBILE NUMBER(19,0), 
	STATUS NUMBER(1,0), 
	TYP NUMBER(1,0), 
	FK_ACC_ID NUMBER(19,0), 
	
	PRIMARY KEY (ID) ENABLE, 
	CONSTRAINT FK_SMS_ACC_ID FOREIGN KEY (FK_ACC_ID) REFERENCES  ACC (ID) ENABLE
   )
/


CREATE TABLE  TKT 
   (	
    ID NUMBER(19,0) NOT NULL ENABLE, 
	CRTD_TIME TIMESTAMP (6), 
	AMT NUMBER(19,2), 
	FRM_STN VARCHAR2(255 CHAR), 
	TO_STN VARCHAR2(255 CHAR),
	NO_OF_TKT NUMBER(19,0),
  	FK_IN_TKT_SMS_ID NUMBER(19,0), 
  	FK_OUT_TKT_SMS_ID NUMBER(19,0), 
	
	PRIMARY KEY (ID) ENABLE,
    CONSTRAINT FK_IN_TKT_SMS_ID FOREIGN KEY (FK_IN_TKT_SMS_ID) REFERENCES  SMS (ID) ENABLE,
    CONSTRAINT FK_OUT_TKT_SMS_ID FOREIGN KEY (FK_OUT_TKT_SMS_ID) REFERENCES  SMS (ID) ENABLE
   )
/


CREATE TABLE  TRN 
   (	
    ID NUMBER(19,0) NOT NULL ENABLE, 
	AMT NUMBER(19,2), 
	CRT_TIME TIMESTAMP (6), 
	TRN_TYP NUMBER(1,0), 
	FK_ACC_ID NUMBER(19,0), 
	
	PRIMARY KEY (ID) ENABLE, 
	CONSTRAINT FK_TRN_ACC_ID FOREIGN KEY (FK_ACC_ID) REFERENCES  ACC (ID) ENABLE
   )
/

